namespace BonsaiGenerators.Tables.Generic.Colours
{
    internal class ColoursTooMany : RandomGenerator
    {
        public static readonly RandomTable colours = new()
        {
            "Absolute Zero",
            "Acid green",
            "Aero blue",
            "Aero",
            "African violet",
            "Air Force blue",
            "Air superiority blue",
            "Alabama crimson",
            "Alice blue",
            "Alien Armpit",
            "Alizarin crimson",
            "Alloy orange",
            "Almond",
            "Amaranth deep purple",
            "Amaranth pink",
            "Amaranth purple",
            "Amaranth red",
            "Amaranth",
            "Amazon",
            "Amber",
            "American rose",
            "Amethyst",
            "Android green",
            "Anti-flash white",
            "Antique brass",
            "Antique bronze",
            "Antique fuchsia",
            "Antique ruby",
            "Antique white",
            "Ao",
            "Apple green",
            "Apricot",
            "Aqua",
            "Aquamarine",
            "Arctic lime",
            "Army green",
            "Arsenic",
            "Artichoke",
            "Arylide yellow",
            "Ash grey",
            "Asparagus",
            "Atomic tangerine",
            "Auburn",
            "Aureolin",
            "AuroMetalSaurus",
            "Avocado",
            "Aztec Gold",
            "Azure mist",
            "Azure",
            "Azureish white",
            "B'dazzled blue",
            "Baby blue eyes",
            "Baby blue",
            "Baby pink",
            "Baby powder",
            "Baker-Miller pink",
            "Ball blue",
            "Banana Mania",
            "Banana yellow",
            "Bangladesh green",
            "Barbie pink",
            "Barn red",
            "Battery Charged Blue",
            "Battleship grey",
            "Bazaar",
            "Beau blue",
            "Beaver",
            "Beige",
            "Big dip o’ruby",
            "Big Foot Feet",
            "Bisque",
            "Bistre brown",
            "Bistre",
            "Bitter lemon",
            "Bitter lime",
            "Bittersweet shimmer",
            "Bittersweet",
            "Black bean",
            "Black Coral",
            "Black leather jacket",
            "Black olive",
            "Black Shadows",
            "Black",
            "Blanched almond",
            "Blast-off bronze",
            "Bleu de France",
            "Blizzard Blue",
            "Blond",
            "Blue Bell",
            "Blue Bolt",
            "Blue Jeans",
            "Blue Lagoon",
            "Blue sapphire",
            "Blue yonder",
            "Blue",
            "Blue-gray",
            "Blue-green",
            "Blue-magenta violet",
            "Blue-violet",
            "Blueberry",
            "Bluebonnet",
            "Blush",
            "Bole",
            "Bondi blue",
            "Bone",
            "Booger Buster",
            "Boston University Red",
            "Bottle green",
            "Boysenberry",
            "Brandeis blue",
            "Brass",
            "Brick red",
            "Bright cerulean",
            "Bright green",
            "Bright lavender",
            "Bright lilac",
            "Bright maroon",
            "Bright navy blue",
            "Bright pink",
            "Bright turquoise",
            "Bright ube",
            "Bright Yellow",
            "Brilliant azure",
            "Brilliant lavender",
            "Brilliant rose",
            "Brink pink",
            "British racing green",
            "Bronze Yellow",
            "Bronze",
            "Brown Sugar",
            "Brown Yellow",
            "Brown",
            "Brown-nose",
            "Brunswick green",
            "Bubble gum",
            "Bubbles",
            "Bud green",
            "Buff",
            "Bulgarian rose",
            "Burgundy",
            "Burlywood",
            "Burnished Brown",
            "Burnt orange",
            "Burnt sienna",
            "Burnt umber",
            "Byzantine",
            "Byzantium",
            "Cadet blue",
            "Cadet grey",
            "Cadet",
            "Cadmium green",
            "Cadmium orange",
            "Cadmium red",
            "Cadmium yellow",
            "Café au lait",
            "Café noir",
            "Cal Poly green",
            "Cambridge Blue",
            "Camel",
            "Cameo pink",
            "Camouflage green",
            "Canary yellow",
            "Canary",
            "Candy apple red",
            "Candy pink",
            "Capri",
            "Caput mortuum",
            "Cardinal",
            "Caribbean green",
            "Carmine pink",
            "Carmine red",
            "Carmine",
            "Carnation pink",
            "Carnelian",
            "Carolina blue",
            "Carrot orange",
            "Castleton green",
            "Catalina blue",
            "Catawba",
            "Cedar Chest",
            "Ceil",
            "Celadon blue",
            "Celadon green",
            "Celadon",
            "Celeste",
            "Celestial blue",
            "Cerise pink",
            "Cerise",
            "Cerulean blue",
            "Cerulean frost",
            "Cerulean",
            "CG Blue",
            "CG Red",
            "Chamoisee",
            "Champagne pink",
            "Champagne",
            "Charcoal",
            "Charleston green",
            "Charm pink",
            "Chartreuse",
            "Cherry blossom pink",
            "Cherry",
            "Chestnut",
            "China pink",
            "China rose",
            "Chinese red",
            "Chinese violet",
            "Chlorophyll green",
            "Chocolate",
            "Chrome yellow",
            "Cinereous",
            "Cinnabar",
            "Cinnamon Satin",
            "Cinnamon[citation needed]",
            "Citrine",
            "Citron",
            "Claret",
            "Classic rose",
            "Cobalt Blue",
            "Cocoa brown",
            "Coconut",
            "Coffee",
            "Columbia Blue",
            "Congo pink",
            "Cool Black",
            "Cool grey",
            "Copper penny",
            "Copper red",
            "Copper rose",
            "Copper",
            "Coquelicot",
            "Coral pink",
            "Coral red",
            "Coral Reef",
            "Coral",
            "Cordovan",
            "Corn",
            "Cornell Red",
            "Cornflower blue",
            "Cornsilk",
            "Cosmic Cobalt",
            "Cosmic latte",
            "Cotton candy",
            "Coyote brown",
            "Cream",
            "Crimson glory",
            "Crimson red",
            "Crimson",
            "Cultured",
            "Cyan azure",
            "Cyan cobalt blue",
            "Cyan cornflower blue",
            "Cyan",
            "Cyan-blue azure",
            "Cyber grape",
            "Cyber yellow",
            "Daffodil",
            "Dandelion",
            "Dark blue",
            "Dark blue-gray",
            "Dark brown",
            "Dark brown-tangelo",
            "Dark byzantium",
            "Dark candy apple red",
            "Dark cerulean",
            "Dark chestnut",
            "Dark coral",
            "Dark cyan",
            "Dark electric blue",
            "Dark goldenrod",
            "Dark gray",
            "Dark green",
            "Dark gunmetal",
            "Dark imperial blue",
            "Dark jungle green",
            "Dark khaki",
            "Dark lava",
            "Dark lavender",
            "Dark liver",
            "Dark magenta",
            "Dark medium gray",
            "Dark midnight blue",
            "Dark moss green",
            "Dark olive green",
            "Dark orange",
            "Dark orchid",
            "Dark pastel blue",
            "Dark pastel green",
            "Dark pastel purple",
            "Dark pastel red",
            "Dark pink",
            "Dark powder blue",
            "Dark puce",
            "Dark purple",
            "Dark raspberry",
            "Dark red",
            "Dark salmon",
            "Dark scarlet",
            "Dark sea green",
            "Dark sienna",
            "Dark sky blue",
            "Dark slate blue",
            "Dark slate gray",
            "Dark spring green",
            "Dark tan",
            "Dark tangerine",
            "Dark taupe",
            "Dark terra cotta",
            "Dark turquoise",
            "Dark vanilla",
            "Dark violet",
            "Dark yellow",
            "Dartmouth green",
            "Davy's grey",
            "Debian red",
            "Deep aquamarine",
            "Deep carmine pink",
            "Deep carmine",
            "Deep carrot orange",
            "Deep cerise",
            "Deep champagne",
            "Deep chestnut",
            "Deep coffee",
            "Deep fuchsia",
            "Deep Green",
            "Deep green-cyan turquoise",
            "Deep jungle green",
            "Deep koamaru",
            "Deep lemon",
            "Deep lilac",
            "Deep magenta",
            "Deep maroon",
            "Deep mauve",
            "Deep moss green",
            "Deep peach",
            "Deep pink",
            "Deep puce",
            "Deep Red",
            "Deep ruby",
            "Deep saffron",
            "Deep sky blue",
            "Deep Space Sparkle",
            "Deep spring bud",
            "Deep Taupe",
            "Deep Tuscan red",
            "Deep violet",
            "Deer",
            "Denim",
            "Desaturated cyan",
            "Desert sand",
            "Desert",
            "Desire",
            "Diamond",
            "Dim gray",
            "Dingy Dungeon",
            "Dirt",
            "Dodger blue",
            "Dogwood rose",
            "Dollar bill",
            "Dolphin Gray",
            "Donkey brown",
            "Drab",
            "Duke blue",
            "Dust storm",
            "Dutch white",
            "Earth yellow",
            "Ebony",
            "Ecru",
            "Eerie black",
            "Eggplant",
            "Eggshell",
            "Egyptian blue",
            "Electric blue",
            "Electric crimson",
            "Electric cyan",
            "Electric green",
            "Electric indigo",
            "Electric lavender",
            "Electric lime",
            "Electric purple",
            "Electric ultramarine",
            "Electric violet",
            "Electric yellow",
            "Emerald",
            "Eminence",
            "English green",
            "English lavender",
            "English red",
            "English violet",
            "Eton blue",
            "Eucalyptus",
            "Fallow",
            "Falu red",
            "Fandango pink",
            "Fandango",
            "Fashion fuchsia",
            "Fawn",
            "Feldgrau",
            "Feldspar",
            "Fern green",
            "Ferrari Red",
            "Field drab",
            "Fiery Rose",
            "Fire engine red",
            "Firebrick",
            "Flame",
            "Flamingo pink",
            "Flattery",
            "Flavescent",
            "Flax",
            "Flirt",
            "Floral white",
            "Fluorescent orange",
            "Fluorescent pink",
            "Fluorescent yellow",
            "Folly",
            "Forest green",
            "French beige",
            "French bistre",
            "French blue",
            "French fuchsia",
            "French lilac",
            "French lime",
            "French mauve",
            "French pink",
            "French plum",
            "French puce",
            "French raspberry",
            "French rose",
            "French sky blue",
            "French violet",
            "French wine",
            "Fresh Air",
            "Frostbite",
            "Fuchsia pink",
            "Fuchsia purple",
            "Fuchsia rose",
            "Fuchsia",
            "Fulvous",
            "Gainsboro",
            "Fuzzy Wuzzy",
            "Gamboge orange",
            "Gamboge",
            "Gargoyle Gas",
            "Generic viridian",
            "Ghost white",
            "Giant's Club",
            "Giants orange",
            "Ginger",
            "Glaucous",
            "Glitter",
            "Glossy Grape",
            "GO green",
            "Gold Fusion",
            "Gold",
            "Golden brown",
            "Golden poppy",
            "Golden yellow",
            "Goldenrod",
            "Granite Gray",
            "Granny Smith Apple",
            "Grape",
            "Gray",
            "Gray-asparagus",
            "Gray-blue",
            "Green Lizard",
            "Green Sheen",
            "Green",
            "Green-blue",
            "Green-cyan",
            "Green-yellow",
            "Grizzly",
            "Grullo",
            "Gunmetal",
            "Guppie green",
            "Halayà úbe",
            "Han blue",
            "Han purple",
            "Hansa yellow",
            "Harlequin green",
            "Harlequin",
            "Harvard crimson",
            "Harvest gold",
            "Heart Gold",
            "Heat Wave",
            "Heidelberg Red [1]",
            "Heliotrope gray",
            "Heliotrope magenta",
            "Heliotrope",
            "Hollywood cerise",
            "Honeydew",
            "Honolulu blue",
            "Hooker's green",
            "Hot magenta",
            "Hot pink",
            "Hunter green",
            "Iceberg",
            "Icterine",
            "Illuminating Emerald",
            "Imperial blue",
            "Imperial purple",
            "Imperial red",
            "Imperial",
            "Inchworm",
            "Independence",
            "India green",
            "Indian red",
            "Indian yellow",
            "Indigo dye",
            "Indigo",
            "Infra Red",
            "International Klein Blue",
            "International orange",
            "Iris",
            "Irresistible",
            "Isabelline",
            "Islamic green",
            "Italian sky blue",
            "Ivory",
            "Jade",
            "Japanese carmine",
            "Japanese indigo",
            "Japanese violet",
            "Jasmine",
            "Jasper",
            "Jazzberry jam",
            "Jelly Bean",
            "Jet",
            "Jonquil",
            "Jordy blue",
            "June bud",
            "Jungle green",
            "Kelly green",
            "Kenyan copper",
            "Keppel",
            "Key Lime",
            "Khaki",
            "Kiwi",
            "Kobe",
            "Kobi",
            "Kobicha",
            "Kombu green",
            "KSU Purple",
            "KU Crimson",
            "La Salle Green",
            "Languid lavender",
            "Lapis lazuli",
            "Laser Lemon",
            "Laurel green",
            "Lava",
            "Lavender blue",
            "Lavender blush",
            "Lavender gray",
            "Lavender indigo",
            "Lavender magenta",
            "Lavender mist",
            "Lavender pink",
            "Lavender purple",
            "Lavender rose",
            "Lavender",
            "Lawn green",
            "Lemon chiffon",
            "Lemon curry",
            "Lemon glacier",
            "Lemon lime",
            "Lemon meringue",
            "Lemon yellow",
            "Lemon",
            "Lenurple",
            "Liberty",
            "Licorice",
            "Light apricot",
            "Light blue",
            "Light brilliant red",
            "Light brown",
            "Light carmine pink",
            "Light cobalt blue",
            "Light coral",
            "Light cornflower blue",
            "Light crimson",
            "Light cyan",
            "Light deep pink",
            "Light French beige",
            "Light fuchsia pink",
            "Light goldenrod yellow",
            "Light gray",
            "Light grayish magenta",
            "Light green",
            "Light hot pink",
            "Light khaki",
            "Light medium orchid",
            "Light moss green",
            "Light orchid",
            "Light pastel purple",
            "Light pink",
            "Light red ochre",
            "Light salmon pink",
            "Light salmon",
            "Light sea green",
            "Light sky blue",
            "Light slate gray",
            "Light steel blue",
            "Light taupe",
            "Light Thulian pink",
            "Light yellow",
            "Lilac Luster",
            "Lilac",
            "Lime green",
            "Lime",
            "Limerick",
            "Lincoln green",
            "Linen",
            "Lion",
            "Liseran purple",
            "Little boy blue",
            "Liver chestnut",
            "Liver",
            "Livid",
            "Lumber",
            "Lust",
            "Macaroni and Cheese",
            "Madder Lake",
            "Magenta haze",
            "Magenta",
            "Magenta-pink",
            "Magic mint",
            "Magic Potion",
            "Magnolia",
            "Mahogany",
            "Maize",
            "Majorelle Blue",
            "Malachite",
            "Manatee",
            "Mandarin",
            "Mango Tango",
            "Mantis",
            "Mardi Gras",
            "Marigold",
            "Maroon",
            "Mauve taupe",
            "Mauve",
            "Mauvelous",
            "Maximum Blue Green",
            "Maximum Blue Purple",
            "Maximum Blue",
            "Maximum Green Yellow",
            "Maximum Green",
            "Maximum Purple",
            "Maximum Red Purple",
            "Maximum Red",
            "Maximum Yellow Red",
            "Maximum Yellow",
            "May green",
            "Maya blue",
            "Meat brown",
            "Medium aquamarine",
            "Medium blue",
            "Medium candy apple red",
            "Medium carmine",
            "Medium champagne",
            "Medium electric blue",
            "Medium jungle green",
            "Medium lavender magenta",
            "Medium orchid",
            "Medium Persian blue",
            "Medium purple",
            "Medium red-violet",
            "Medium ruby",
            "Medium sea green",
            "Medium sky blue",
            "Medium slate blue",
            "Medium spring bud",
            "Medium spring green",
            "Medium taupe",
            "Medium turquoise",
            "Medium Tuscan red",
            "Medium vermilion",
            "Medium violet-red",
            "Mellow apricot",
            "Mellow yellow",
            "Melon",
            "Metallic Seaweed",
            "Metallic Sunburst",
            "Mexican pink",
            "Middle Blue Green",
            "Middle Blue Purple",
            "Middle Blue",
            "Middle Green Yellow",
            "Middle Green",
            "Middle Purple",
            "Middle Red Purple",
            "Middle Red",
            "Middle Yellow Red",
            "Middle Yellow",
            "Midnight blue",
            "Midnight green",
            "Midnight",
            "Mikado yellow",
            "Mimi Pink",
            "Mindaro",
            "Ming",
            "Minion Yellow",
            "Mint cream",
            "Mint green",
            "Mint",
            "Misty Moss",
            "Misty rose",
            "Moccasin",
            "Mode beige",
            "Moonstone blue",
            "Mordant red 19",
            "Moss green",
            "Mountain Meadow",
            "Mountbatten pink",
            "MSU Green",
            "Mughal green",
            "Mulberry",
            "Mummy's Tomb",
            "Mustard",
            "Myrtle green",
            "Mystic Maroon",
            "Mystic",
            "Nadeshiko pink",
            "Napier green",
            "Naples yellow",
            "Navajo white",
            "Navy purple",
            "Navy",
            "Neon Carrot",
            "Neon fuchsia",
            "Neon green",
            "New Car",
            "New York pink",
            "Nickel",
            "Non-photo blue",
            "North Texas Green",
            "Nyanza",
            "Ocean Blue",
            "Ocean Boat Blue",
            "Ocean Green",
            "Ochre",
            "Office green",
            "Ogre Odor",
            "Old burgundy",
            "Old gold",
            "Old heliotrope",
            "Old lace",
            "Old lavender",
            "Old mauve",
            "Old moss green",
            "Old rose",
            "Old silver",
            "Olive Drab #7",
            "Olive Drab",
            "Olive",
            "Olivine",
            "Onyx",
            "Opera mauve",
            "Orange peel",
            "Orange Soda",
            "Orange",
            "Orange-red",
            "Orange-yellow",
            "Orchid pink",
            "Orchid",
            "Orioles orange",
            "Otter brown",
            "OU Crimson Red",
            "Outer Space",
            "Outrageous Orange",
            "Oxford Blue",
            "Pacific Blue",
            "Pakistan green",
            "Palatinate blue",
            "Palatinate purple",
            "Pale aqua",
            "Pale blue",
            "Pale brown",
            "Pale carmine",
            "Pale cerulean",
            "Pale chestnut",
            "Pale copper",
            "Pale cornflower blue",
            "Pale cyan",
            "Pale gold",
            "Pale goldenrod",
            "Pale green",
            "Pale lavender",
            "Pale magenta",
            "Pale magenta-pink",
            "Pale pink",
            "Pale plum",
            "Pale red-violet",
            "Pale robin egg blue",
            "Pale silver",
            "Pale spring bud",
            "Pale taupe",
            "Pale turquoise",
            "Pale violet",
            "Pale violet-red",
            "Palm Leaf",
            "Pansy purple",
            "Paolo Veronese green",
            "Papaya whip",
            "Paradise pink",
            "Paris Green",
            "Parrot Pink",
            "Pastel blue",
            "Pastel brown",
            "Pastel gray",
            "Pastel green",
            "Pastel magenta",
            "Pastel orange",
            "Pastel pink",
            "Pastel purple",
            "Pastel red",
            "Pastel violet",
            "Pastel yellow",
            "Patriarch",
            "Payne's grey",
            "Peach puff",
            "Peach",
            "Peach-orange",
            "Peach-yellow",
            "Pear",
            "Pearl Aqua",
            "Pearl",
            "Pearly purple",
            "Peridot",
            "Periwinkle",
            "Permanent Geranium Lake",
            "Persian blue",
            "Persian green",
            "Persian indigo",
            "Persian orange",
            "Persian pink",
            "Persian plum",
            "Persian red",
            "Persian rose",
            "Persimmon",
            "Peru",
            "Pewter Blue",
            "Phlox",
            "Phthalo blue",
            "Phthalo green",
            "Picton blue",
            "Pictorial carmine",
            "Piggy pink",
            "Pine green",
            "Pineapple",
            "Pink Flamingo",
            "Pink lace",
            "Pink lavender",
            "Pink pearl",
            "Pink raspberry",
            "Pink Sherbet",
            "Pink",
            "Pink-orange",
            "Pistachio",
            "Pixie Powder",
            "Platinum",
            "Plum",
            "Plump Purple",
            "Polished Pine",
            "Pomp and Power",
            "Popstar",
            "Portland Orange",
            "Powder blue",
            "Princess Perfume",
            "Princeton orange",
            "Prune",
            "Prussian blue",
            "Psychedelic purple",
            "Puce red",
            "Puce",
            "Pullman Brown",
            "Pullman Green",
            "Pumpkin",
            "Purple Heart",
            "Purple mountain majesty",
            "Purple navy",
            "Purple pizzazz",
            "Purple Plum",
            "Purple taupe",
            "Purple",
            "Purpureus",
            "Quartz",
            "Queen blue",
            "Queen pink",
            "Quick Silver",
            "Quinacridone magenta",
            "Rackley",
            "Radical Red",
            "Raisin black",
            "Rajah",
            "Raspberry glace",
            "Raspberry pink",
            "Raspberry rose",
            "Raspberry",
            "Raw Sienna",
            "Raw umber",
            "Razzle dazzle rose",
            "Razzmatazz",
            "Razzmic Berry",
            "Rebecca Purple",
            "Red devil",
            "Red Salsa",
            "Red",
            "Red-brown",
            "Red-orange",
            "Red-purple",
            "Red-violet",
            "Redwood",
            "Regalia",
            "Registration black",
            "Resolution blue",
            "Rhythm",
            "Rich black",
            "Rich brilliant lavender",
            "Rich carmine",
            "Rich electric blue",
            "Rich lavender",
            "Rich lilac",
            "Rich maroon",
            "Rifle green",
            "Roast coffee",
            "Robin egg blue",
            "Rocket metallic",
            "Roman silver",
            "Rose bonbon",
            "Rose Dust",
            "Rose ebony",
            "Rose gold",
            "Rose madder",
            "Rose pink",
            "Rose quartz",
            "Rose red",
            "Rose taupe",
            "Rose vale",
            "Rose",
            "Rosewood",
            "Rosso corsa",
            "Rosy brown",
            "Royal azure",
            "Royal blue",
            "Royal fuchsia",
            "Royal purple",
            "Royal yellow",
            "Ruber",
            "Rubine red",
            "Ruby red",
            "Ruby",
            "Ruddy brown",
            "Ruddy pink",
            "Ruddy",
            "Rufous",
            "Russet",
            "Russian green",
            "Russian violet",
            "Rust",
            "Rusty red",
            "Sacramento State green",
            "Saddle brown",
            "Safety orange",
            "Safety yellow",
            "Saffron",
            "Sage",
            "Salmon pink",
            "Salmon",
            "Sand dune",
            "Sand",
            "Sandstorm",
            "Sandy brown",
            "Sandy Tan",
            "Sandy taupe",
            "Sangria",
            "Sap green",
            "Sapphire blue",
            "Sapphire",
            "Sasquatch Socks",
            "Satin sheen gold",
            "Scarlet",
            "Schauss pink",
            "School bus yellow",
            "Screamin' Green",
            "Sea blue",
            "Sea Foam Green",
            "Sea green",
            "Sea Serpent",
            "Seal brown",
            "Seashell",
            "Selective yellow",
            "Sepia",
            "Shadow blue",
            "Shadow",
            "Shampoo",
            "Shamrock green",
            "Sheen Green",
            "Shimmering Blush",
            "Shiny Shamrock",
            "Shocking pink",
            "Sienna",
            "Silver chalice",
            "Silver Lake blue",
            "Silver pink",
            "Silver sand",
            "Silver",
            "Sinopia",
            "Sizzling Red",
            "Sizzling Sunset",
            "Skobeloff",
            "Sky blue",
            "Sky magenta",
            "Slate blue",
            "Slate gray",
            "Smalt",
            "Smitten",
            "Smoke",
            "Smokey Topaz",
            "Smoky black",
            "Smoky Topaz",
            "Snow",
            "Soap",
            "Solid pink",
            "Sonic silver",
            "Space cadet",
            "Spanish bistre",
            "Spanish blue",
            "Spanish carmine",
            "Spanish crimson",
            "Spanish gray",
            "Spanish green",
            "Spanish orange",
            "Spanish pink",
            "Spanish red",
            "Spanish sky blue",
            "Spanish violet",
            "Spanish viridian",
            "Spartan Crimson",
            "Spicy mix",
            "Spiro Disco Ball",
            "Spring bud",
            "Spring Frost",
            "Spring green",
            "St. Patrick's blue",
            "Star command blue",
            "Steel blue",
            "Steel pink",
            "Steel Teal",
            "Stil de grain yellow",
            "Stizza",
            "Stormcloud",
            "Straw",
            "Strawberry",
            "Sugar Plum",
            "Sunburnt Cyclops",
            "Sunglow",
            "Sunny",
            "Sunray",
            "Sunset orange",
            "Sunset",
            "Super pink",
            "Sweet Brown",
            "Tan",
            "Tangelo",
            "Tangerine yellow",
            "Tangerine",
            "Tango pink",
            "Tart Orange",
            "Taupe gray",
            "Taupe",
            "Tea green",
            "Tea rose",
            "Teal blue",
            "Teal deer",
            "Teal green",
            "Teal",
            "Telemagenta",
            "Tenné",
            "Terra cotta",
            "Thistle",
            "Thulian pink",
            "Tickle Me Pink",
            "Tiffany Blue",
            "Tiger's eye",
            "Timberwolf",
            "Titanium yellow",
            "Tomato",
            "Toolbox",
            "Topaz",
            "Tractor red",
            "Trolley Grey",
            "Tropical rain forest",
            "Tropical violet",
            "True Blue",
            "Tufts Blue",
            "Tulip",
            "Tumbleweed",
            "Turkish rose",
            "Turquoise blue",
            "Turquoise green",
            "Turquoise Surf",
            "Turquoise",
            "Turtle green",
            "Tuscan brown",
            "Tuscan red",
            "Tuscan tan",
            "Tuscan",
            "Tuscany",
            "Twilight lavender",
            "Tyrian purple",
            "UA blue",
            "UA red",
            "Ube",
            "UCLA Blue",
            "UCLA Gold",
            "UFO Green",
            "Ultra pink",
            "Ultra red",
            "Ultramarine blue",
            "Ultramarine",
            "Umber",
            "Unbleached silk",
            "United Nations blue",
            "University of California Gold",
            "University of Tennessee Orange",
            "Unmellow yellow",
            "UP Forest green",
            "UP Maroon",
            "Upsdell red",
            "Urobilin",
            "USAFA blue",
            "USC Cardinal",
            "USC Gold",
            "Utah Crimson",
            "Van Dyke Brown",
            "Vanilla ice",
            "Vanilla",
            "Vegas gold",
            "Venetian red",
            "Verdigris",
            "Vermilion",
            "Veronica",
            "Very light azure",
            "Very light blue",
            "Very light malachite green",
            "Very light tangelo",
            "Very pale orange",
            "Very pale yellow",
            "Violet",
            "Violet-blue",
            "Violet-red",
            "Viridian green",
            "Viridian",
            "Vista blue",
            "Vivid amber",
            "Vivid auburn",
            "Vivid burgundy",
            "Vivid cerise",
            "Vivid cerulean",
            "Vivid crimson",
            "Vivid gamboge",
            "Vivid lime green",
            "Vivid malachite",
            "Vivid mulberry",
            "Vivid orange peel",
            "Vivid orange",
            "Vivid orchid",
            "Vivid raspberry",
            "Vivid red",
            "Vivid red-tangelo",
            "Vivid sky blue",
            "Vivid tangelo",
            "Vivid tangerine",
            "Vivid vermilion",
            "Vivid violet",
            "Vivid yellow",
            "Volt",
            "Warm black",
            "Waterspout",
            "Weldon Blue",
            "Wenge",
            "Wheat",
            "White smoke",
            "White",
            "Wild blue yonder",
            "Wild orchid",
            "Wild Strawberry",
            "Wild watermelon",
            "Willpower orange",
            "Windsor tan",
            "Wine dregs",
            "Wine",
            "Winter Sky",
            "Winter Wizard",
            "Wintergreen Dream",
            "Wisteria",
            "Wood brown",
            "Xanadu",
            "Yale Blue",
            "Yankees blue",
            "Yellow Orange",
            "Yellow rose",
            "Yellow Sunshine",
            "Yellow",
            "Yellow-green",
            "Zaffre",
            "Zinnwaldite brown",
            "Zomp",
        };

        public override string ToString()
        {
            return colours.Next();
        }
    }
}