using System.Collections.Generic;

namespace BonsaiGenerators.Tables.Names.Real.LatinAmerican
{
    internal class LatinAmericanMaleGiven : RandomTable
    {
        public new List<string> Entries
        {
            get { return base.Entries; }

            set
            {
                base.Entries = value;
            }
        }

        public LatinAmericanMaleGiven()
        {
            Entries = new()
            {
                "Abel",
                "Abelardo",
                "Adelmár",
                "Adriano",
                "Adrián",
                "Adán",
                "Agustín",
                "Alan",
                "Alberto",
                "Aldo",
                "Alejandro",
                "Alejo",
                "Alexander",
                "Alfonso",
                "Alfredo",
                "Alonso",
                "Amado",
                "Andrés",
                "Andrés Felipe",
                "Anthony",
                "Antonio",
                "Antón",
                "Aníbal",
                "Ariel",
                "Aristides",
                "Armando",
                "Arnaldo",
                "Arnoldo",
                "Arturo",
                "Asier",
                "Atilio",
                "Augusto",
                "Augustín",
                "Aurelio",
                "Axel",
                "Baltasar",
                "Baltazar",
                "Beltrán",
                "Benito",
                "Benjamín",
                "Bernardo",
                "Bertrán",
                "Braulio",
                "Breno",
                "Bruno",
                "Caetano",
                "Camilo",
                "Carlos",
                "Carlos Alberto",
                "Carlos Andrés",
                "Carlos Roberto",
                "Cayetano",
                "Caín",
                "Cecilio",
                "Celio",
                "Celso",
                "Christian",
                "Cipriano",
                "Ciro",
                "Claudio",
                "Clemente",
                "Constantino",
                "Cristiano",
                "Cristián",
                "Cristopher",
                "Cristóbal",
                "César",
                "Damián",
                "Daniel",
                "Danilo",
                "Dante",
                "Darío",
                "David",
                "Demián",
                "Denis",
                "Diego",
                "Domingo",
                "Duilio",
                "Edgar",
                "Edmundo",
                "Eduardo",
                "Edwin",
                "Efraín",
                "Elián",
                "Eloy",
                "Elías",
                "Emanuel",
                "Emiliano",
                "Emilio",
                "Emmanuel",
                "Enrique",
                "Eric",
                "Erico",
                "Erik",
                "Ernesto",
                "Esteban",
                "Estefano",
                "Eugenio",
                "Evandro",
                "Evaristo",
                "Ezequiel",
                "Fabiano",
                "Fabio",
                "Fabián",
                "Fabricio",
                "Facundo",
                "Fantino",
                "Fausto",
                "Federico",
                "Feliciano",
                "Felipe",
                "Fermín",
                "Fernando",
                "Fidel",
                "Francisco",
                "Francisco Javier",
                "Franco",
                "Franklin",
                "Félix",
                "Gabino",
                "Gabriel",
                "Gael",
                "Gastón",
                "Genaro",
                "Gerardo",
                "Germán",
                "Gilberto",
                "Giovanni",
                "Giovany",
                "Gonzalo",
                "Guido",
                "Guillermo",
                "Gustavo",
                "Helio",
                "Hernando",
                "Hernán",
                "Hidalgo",
                "Hilario",
                "Homero",
                "Honorio",
                "Horacio",
                "Hugo",
                "Humberto",
                "Héctor",
                "Ian",
                "Ignacio",
                "Isaac",
                "Isaías",
                "Ismael",
                "Israel",
                "Iván",
                "Iñigo",
                "Jacinto",
                "Jacob",
                "Jacobo",
                "Jael",
                "Jaime",
                "Jairo",
                "Javier",
                "Javier Pedro",
                "Jenaro",
                "Jeremías",
                "Jerónimo",
                "Jesús",
                "Joaquín",
                "Joel",
                "Jonathan",
                "Jonatán",
                "Jorge",
                "Jorge Alberto",
                "Jorge Luis",
                "Josué",
                "José Adán",
                "José Antonio",
                "José Luis",
                "José María",
                "Juan",
                "Juan Carlos",
                "Juan Esteban",
                "Juan Ignacio",
                "Juan José",
                "Juan Manuel",
                "Juan Pablo",
                "Juan Román",
                "Juan Sebastián",
                "Julio",
                "Julio César",
                "Julián",
                "Justino",
                "Justo",
                "Kevin",
                "Lauro",
                "Leandro",
                "Leonardo",
                "Leonel",
                "Leopoldo",
                "León",
                "Leónidas",
                "Lionel",
                "Lorenzo",
                "Luca",
                "Lucas",
                "Luciano",
                "Luis",
                "Luis Alberto",
                "Luis Antonio",
                "Luis Enrique",
                "Luis Fernando",
                "Manrique",
                "Manuel",
                "Marcel",
                "Marcelo",
                "Marco",
                "Marco Antonio",
                "Marcos",
                "Mariano",
                "Mario",
                "Marlón",
                "Martín",
                "Mateo",
                "Matías",
                "Mauricio",
                "Mauro",
                "Max",
                "Maximiliano",
                "Miguel",
                "Miguel Ángel",
                "Modesto",
                "Moisés",
                "Máximo",
                "Narciso",
                "Natanael",
                "Nelson",
                "Nicolás",
                "Noel",
                "Norberto",
                "Nulpi",
                "Néstor",
                "Octavio",
                "Omar",
                "Orlando",
                "Osvaldo",
                "Otilio",
                "Otón",
                "Pablo",
                "Pablo César",
                "Pascal",
                "Pascual",
                "Patricio",
                "Paulo",
                "Pedro",
                "Plácido",
                "Rafael",
                "Raimundo",
                "Ramiro",
                "Ramón",
                "Raymundo",
                "Raúl",
                "Reinaldo",
                "Renato",
                "Renán",
                "Reynaldo",
                "Ricardo",
                "Roberto",
                "Rodolfo",
                "Rodrigo",
                "Rogelio",
                "Rolando",
                "Romeo",
                "Román",
                "Roque",
                "Roy",
                "Rubén",
                "Rómulo",
                "Salvador",
                "Samuel",
                "Santiago",
                "Saúl",
                "Sebastián",
                "Sergio",
                "Silvestre",
                "Silvino",
                "Silvio",
                "Simón",
                "Tadeo",
                "Telmo",
                "Teo",
                "Teodoro",
                "Thiago",
                "Tobías",
                "Tomás",
                "Ulises",
                "Uriel",
                "Valentino",
                "Valentín",
                "Valerio",
                "Vicente",
                "Victorio",
                "Vinicio",
                "Virgilio",
                "Víctor",
                "Víctor Hugo",
                "Víctor Manuel",
                "Walter",
                "Wilfred",
                "Wilfredo",
                "William",
                "Wilson",
                "Xavier",
                "Yago",
                "Zacarías",
                "Álvaro",
                "Ángel",
                "Óscar",
            };
        }
    }
}