using System.Collections.Generic;

namespace BonsaiGenerators.Tables.Names.Real.LatinAmerican
{
    internal class LatinAmericanFemaleGiven : RandomTable
    {
        public new List<string> Entries
        {
            get { return base.Entries; }

            set
            {
                base.Entries = value;
            }
        }

        public LatinAmericanFemaleGiven()
        {
            Entries = new()
            {
                "Abigail",
                "Ada",
                "Adriana",
                "Agustina",
                "Aitana",
                "Alba",
                "Aleja",
                "Alejandra",
                "Alexa",
                "Alicia",
                "Allison",
                "Alma",
                "Amalia",
                "Amanda",
                "Amelia",
                "Ana",
                "Ana Lucía",
                "Ana María",
                "Ana Sofía",
                "Anabel",
                "Anaís",
                "Andrea",
                "Angelina",
                "Angélica",
                "Antonella",
                "Antonia",
                "Antonia María",
                "Ariana",
                "Astrid",
                "Aurora",
                "Beatriz",
                "Belinda",
                "Belisa",
                "Belén",
                "Berta",
                "Bianca",
                "Blanca",
                "Brianna",
                "Bárbara",
                "Camelia",
                "Camila",
                "Candela",
                "Carina",
                "Carla",
                "Carlota",
                "Carmen",
                "Carolina",
                "Casandra",
                "Catalina",
                "Caterina",
                "Cecilia",
                "Celeste",
                "Celia",
                "Clara",
                "Clarisa",
                "Claudia",
                "Claudia Andrea",
                "Constanza",
                "Coral",
                "Cristela",
                "Cristina",
                "Cíntia",
                "Dacia",
                "Dafne",
                "Dalia",
                "Daniela",
                "Danna",
                "Delfina",
                "Delia",
                "Desirée",
                "Diana",
                "Dina",
                "Dolores",
                "Dominique",
                "Doménica",
                "Doris",
                "Débora",
                "Edith",
                "Elba",
                "Elena",
                "Eleonor",
                "Eleonora",
                "Elia",
                "Eliana",
                "Elisa",
                "Elizabeth",
                "Elsa",
                "Elvira",
                "Ema",
                "Emilia",
                "Emma",
                "Erica",
                "Esmeralda",
                "Esperanza",
                "Estefanía",
                "Estela",
                "Ester",
                "Estrella",
                "Eugenia",
                "Eulalia",
                "Evangelina",
                "Evelina",
                "Evelyn",
                "Fabia",
                "Fabiana",
                "Fabiola",
                "Fanny",
                "Federica",
                "Felicia",
                "Felisa",
                "Fermina",
                "Fernanda",
                "Filomena",
                "Flavia",
                "Flor",
                "Florencia",
                "Francisca",
                "Frida",
                "Fátima",
                "Gabriela",
                "Gala",
                "Galia",
                "Gema",
                "Gemma",
                "Geraldina",
                "Gilda",
                "Giovanna",
                "Gisela",
                "Giselda",
                "Giselle",
                "Gladis",
                "Gloria",
                "Gracia",
                "Graciela",
                "Greta",
                "Guadalupe",
                "Guillermina",
                "Helena",
                "Hilda",
                "Hortensia",
                "Ida",
                "Ileana",
                "Imelda",
                "Ingrid",
                "Inmaculada",
                "Inés",
                "Inés María",
                "Irene",
                "Iris",
                "Irma",
                "Isabel",
                "Isabella",
                "Isadora",
                "Isidora",
                "Isis",
                "Ismelda",
                "Itatí",
                "Ivana",
                "Ivanna",
                "Jacinta",
                "Jamila",
                "Javiera",
                "Jazmín",
                "Jeannette",
                "Jenifer",
                "Jennifer",
                "Jezabel",
                "Jimena",
                "Joana",
                "Josefa",
                "Josefina",
                "Juana",
                "Judit",
                "Judith",
                "Julia",
                "Juliana",
                "Julieta",
                "Jésica",
                "Karen",
                "Karina",
                "Karla",
                "Katia",
                "Kiara",
                "Laila",
                "Lara",
                "Larissa",
                "Laura",
                "Layla",
                "Leila",
                "Leticia",
                "Lidia",
                "Lilia",
                "Lilian",
                "Liliana",
                "Linda",
                "Livia",
                "Lola",
                "Lorena",
                "Lourdes",
                "Lourdes María",
                "Luana",
                "Luciana",
                "Lucila",
                "Lucía",
                "Luisa",
                "Luisa María",
                "Luna",
                "Luz",
                "Mabel",
                "Magali",
                "Maia",
                "Malvina",
                "Manuela",
                "Marcela",
                "Marcia",
                "Margarita",
                "Margot",
                "Marian",
                "Mariana",
                "Mariana Jesús",
                "Maribel",
                "Maricruz",
                "Mariel",
                "Marina",
                "Marisabel",
                "Marisol",
                "Maritza",
                "Mariángel",
                "Marlene",
                "Marta",
                "Martha",
                "Martina",
                "María Alejandra",
                "María Angelica",
                "María Belén",
                "María Camila",
                "María Carmen",
                "María Cristina",
                "María Eugenia",
                "María Fernanda",
                "María Florencia",
                "María Isabel",
                "María José",
                "María Laura",
                "María Lourdes",
                "María Paula",
                "María Pilar",
                "María Teresa",
                "María Victoria",
                "María Ángeles",
                "Massiel",
                "Matilde",
                "Maya",
                "Mayte",
                "Melania",
                "Melanie",
                "Melinda",
                "Melissa",
                "Mercedes",
                "Micaela",
                "Michelle",
                "Milagros",
                "Milena",
                "Minerva",
                "Miranda",
                "Mireya",
                "Miriam",
                "Monserrat",
                "Montserrat",
                "Morena",
                "Muriel",
                "Myrna",
                "Mélida",
                "Mía",
                "Mónica",
                "Nadia",
                "Naomi",
                "Natalia",
                "Natalie",
                "Natalí",
                "Natasha",
                "Natividad",
                "Nela",
                "Nelly",
                "Nicole",
                "Nieves",
                "Noemí",
                "Nola",
                "Nora",
                "Nuria",
                "Nélida",
                "Ofelia",
                "Olga",
                "Olivia",
                "Oriana",
                "Paloma",
                "Pamela",
                "Paola",
                "Patricia",
                "Paula",
                "Paulina",
                "Paz",
                "Penélope",
                "Perla",
                "Pilar",
                "Priscila",
                "Pía",
                "Rafaela",
                "Ramona",
                "Raquel",
                "Rebeca",
                "Regina",
                "Reina",
                "Renata",
                "Renée",
                "Rita",
                "Roberta",
                "Rocío",
                "Romina",
                "Rosa",
                "Rosa María",
                "Rosalba",
                "Rosalía",
                "Rosana",
                "Rosario",
                "Rosmery",
                "Roxana",
                "Ruth",
                "Sabina",
                "Sabrina",
                "Salomé",
                "Samanta",
                "Sandra",
                "Sara",
                "Selena",
                "Serena",
                "Silvia",
                "Simona",
                "Sofía",
                "Sol",
                "Soledad",
                "Sonia",
                "Soraya",
                "Stefanía",
                "Stella",
                "Stella Maris",
                "Susan",
                "Susana",
                "Talía",
                "Tamara",
                "Tania",
                "Tatiana",
                "Telma",
                "Teresa",
                "Trinidad",
                "Tulia",
                "Uriel",
                "Ursula",
                "Valentina",
                "Valeria",
                "Vanesa",
                "Vera",
                "Verónica",
                "Victoria",
                "Vilma",
                "Violeta",
                "Virginia",
                "Vivian",
                "Viviana",
                "Wilma",
                "Ximena",
                "Yanet",
                "Yanina",
                "Yasmina",
                "Yolanda",
                "Yvonne",
                "Zaida",
                "Zoe",
                "Zoila",
                "Zoraida",
                "Zulema",
                "Zulima",
                "Zulma",
                "Ángela",
            };
        }
    }
}