# This is ".github/workflows/gh-pages.yml" file.
name: github pages deploy

on:
  push:    
    tags:
      - '*'                         
        
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1

      # Sets up node
      - name: setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      # Run npm ci
      - name: npm install (ci)
        working-directory: Bonsai
      - run: npm ci
      
      # Use gulp to run css:prod, purging and minimizing tailwind
      - name: purge and minimize tailwind through gulp 
        working-directory: Bonsai  
      - run: gulp css:prod
        
      # Publish the site
      - name: Publish
        run: dotnet publish Bonsai.sln -c Release -o public -p:GHPages=true

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
