# This is ".github/workflows/gh-pages.yml" file.
name: github pages deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'                         
        
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        
      # Publish the site
      - name: Publish
        run: dotnet publish Bonsai.sln -c Release -o public -p:GHPages=true

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
